version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0  
    container_name: keycloak
    command: start --import-realm  
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_BOOTSTRAP_ADMIN_USERNAME:-admin}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_BOOTSTRAP_ADMIN_PASSWORD:-admin}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID:-}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET:-}
      KC_HOSTNAME: https://deploynest.dev
      KC_HOSTNAME_STRICT: "true"
      KC_PROXY_HEADERS: xforwarded
      KC_HTTP_ENABLED: "true"
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
    ports:
      - "127.0.0.1:8081:8080"   
    volumes:
      - ./doc/myapp-frontend-realm.json:/opt/keycloak/data/import/myapp-frontend-realm.json:ro

  app1:
    image: node:22-alpine
    working_dir: /app
    command: sh -c "node server.js"
    environment:
      PORT: 3000
      KEYCLOAK_URL: http://keycloak:8080
      VITE_KEYCLOAK_URL: https://deploynest.dev
      VITE_KEYCLOAK_REALM: myapp-frontend
      VITE_KEYCLOAK_CLIENT_ID: myapp-frontend
    volumes:
      - ./keycloak-app-SSO:/app
    ports:
      - "3000:3000"
    depends_on:
      - keycloak

  app2:
    image: node:22-alpine
    working_dir: /app
    command: sh -c "node server.js"
    environment:
      PORT: 3001
      KEYCLOAK_URL: http://keycloak:8080
      VITE_KEYCLOAK_URL: https://deploynest.dev
      VITE_KEYCLOAK_REALM: myapp-frontend
      VITE_KEYCLOAK_CLIENT_ID: myapp-frontend-2
    volumes:
      - ./keycloak-app-SSO-2:/app
    ports:
      - "3001:3001"
    depends_on:
      - keycloak
